name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          token: ${{ secrets.USER_TOKEN }}
          owner: blender
          #base: master
          #head: master

      - uses: hmarr/auto-approve-action@v2
        with:
          github-token: "${{ secrets.USER_TOKEN }}"
