  
name: BUILD-RELEASE

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    push:
    branches: [ release ]
  pull_request:
    branches: [ release ]
  workflow_dispatch: # on button click

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      
      - name: Cache build environment
        uses: actions/cache@v2
        env:
          cache-name: ${{ github.ref }}-${{ runner.os }}
        with:
          path: ${{ env.GITHUB_WORKSPACE }}
          key: build-cache-${{ env.cache-name }}
            
      - uses: actions/checkout@v2
      
      - name: Build.py
        run: python build.py
          
      - name: Upload Build
        uses: actions/upload-artifact@v2
        with:
          name: Blender-Release-${{ runner.os }}
          path: ${{ env._MAIN_DIR }}/build_release/bin/

